exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(92A2ECff) rgba(293052ff) 45deg
    col.inactive_border = rgba(03035Fff) rgba(1C1B9Fff) 45deg
}

group {
    col.border_active = rgba(92A2ECff) rgba(293052ff) 45deg
    col.border_inactive = rgba(03035Fcc) rgba(1C1B9Fcc) 45deg
    col.border_locked_active = rgba(DDDDD9ff) rgba(0B0B0Aff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
